FROM node:22.14.0-bullseye-slim

RUN mkdir -p /backend && chown node /backend
USER node
WORKDIR /backend

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

COPY --chown=node:node . .
RUN npm run compile

EXPOSE 5000

CMD ["npm", "run", "start"]
