.PHONY: deploy

#################################################################################
# COMMANDS
#################################################################################

deploy:
	bash gcs-function/scripts/deploy.sh && bash s3-service/scripts/deploy.sh
