services:
    backend:
        depends_on:
            backend-database:
                condition: service_healthy
            backend-database-migrate:
                condition: service_completed_successfully
        image: backend
        ports:
            - 5000:5000
    backend-database:
        build:
            context: ./backend-database
        environment:
            POSTGRES_DB: app-database
            POSTGRES_PASSWORD: app-database-password
            POSTGRES_USER: app-database-user
        image: database
        volumes:
            - backend-database-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U app-database-user -d app-database" ]
            interval: 3s
            timeout: 10s
            retries: 5
    backend-database-migrate:
        build:
            context: ./backend
        command: scripts/db-migrate.js
        depends_on:
            backend-database:
                condition: service_healthy
        image: backend
    frontend:
        build:
            args:
                app_env: production
            context: ./frontend
        image: frontend
        ports:
            - 3000:3000
    marketing:
        build:
            args:
                app_env: production
            context: ./marketing
        image: marketing
        ports:
            - 3002:3000
volumes:
    backend-database-data:
        driver: local
