services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        environment:
            FRONTEND_PORT: ${FRONTEND_PORT}
        command: npm start
        depends_on:
            backend-database:
                condition: service_healthy
            backend-database-migrate:
                condition: service_completed_successfully
        image: backend
        ports:
            - ${BACKEND_PORT}:5000
    backend-database:
        build:
            context: ./backend-database
        environment:
            POSTGRES_DB: app-database
            POSTGRES_PASSWORD: app-database-password
            POSTGRES_USER: app-database-user
        image: database
        volumes:
            - backend-database-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U app-database-user -d app-database" ]
            interval: 3s
            timeout: 10s
            retries: 5
    backend-database-migrate:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        command: sh -c "npm run db:retryable-migrate && npm run db:seed"
        depends_on:
            backend-database:
                condition: service_healthy
        image: backend
    frontend:
        build:
            args:
                app_env: development
            context: ./frontend
            dockerfile: Dockerfile.dev
        environment:
            REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
        image: frontend
        ports:
            - ${FRONTEND_PORT}:3000
volumes:
    backend-database-data:
        driver: local
