steps:
  - id: "Install deps"
    name: node:22.14.0-alpine
    entrypoint: npm
    args: ["ci"]
    dir: "services/frontend"
    env:
      - "CYPRESS_INSTALL_BINARY=0"

  - id: "Run tests and linters"
    name: node:22.14.0-alpine
    entrypoint: npm
    args: ["run", "ci"]
    dir: "services/frontend"

  - id: "Build static assets"
    name: node:22.14.0-alpine
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "REACT_APP_BACKEND_HOST=${_BACKEND_HOST}"
      - "REACT_APP_BACKEND_PORT=${_BACKEND_PORT}"
      - "REACT_APP_BACKEND_PROTOCOL=${_BACKEND_PROTOCOL}"
      - "REACT_APP_MARKETING_HOST=${_MARKETING_HOST}"
      - "REACT_APP_MARKETING_PORT=${_MARKETING_PORT}"
      - "REACT_APP_MARKETING_PROTOCOL=${_MARKETING_PROTOCOL}"
      - "REACT_APP_BRANCH=${BRANCH_NAME}"
    dir: "services/frontend"

  - id: "Deploy to Firebase"
    name: gcr.io/$PROJECT_ID/firebase
    args: ["deploy", "--project=$PROJECT_ID", "--only=hosting:${_FIREBASE_TARGET}"]
    dir: "services/frontend"

substitutions:
  _BACKEND_HOST: "backend.ufincs.com"
  _BACKEND_PORT: "443"
  _BACKEND_PROTOCOL: "https"
  _MARKETING_HOST: "ufincs.com"
  _MARKETING_PORT: "443"
  _MARKETING_PROTOCOL: "https"
  _FIREBASE_TARGET: "frontend"

timeout: 3600s